apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-config
  namespace: weather
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://tempwindx-rds-instance.cps4c4ko8ic6.ap-south-1.rds.amazonaws.com:5432/testdb"
